type Tech =
  | 'Auth0'
  | 'AWS Lambda'
  | 'Backbone.js'
  | 'Bash scripting'
  | 'Bitbucket'
  | 'Chakra-UI'
  | 'Coursera'
  | 'Cypress'
  | 'Docker'
  | 'Docusign'
  | 'Electron.js'
  | 'Expo'
  | 'Express'
  | 'ESLint'
  | 'Firebase'
  | 'Github'
  | 'Gitlab'
  | 'GraphQL'
  | 'Javascript'
  | 'jQuery'
  | 'LinkedIn'
  | 'Mantine'
  | 'MongoDB'
  | 'Next.js'
  | 'Node.js'
  | 'Play Framework'
  | 'Prettier'
  | 'React.js'
  | 'React Native'
  | 'Redux Toolkit'
  | 'Scala'
  | 'Selenium'
  | 'Shell Scripting'
  | 'SQL Server'
  | 'TailwindCSS'
  | 'Typescript'
  | 'Udemy'
  | 'Vite';
