# Simple workflow for deploying website to Vercel
name: Deploy https://manup.dev to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy-to-vercel:
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📥 Install Vercel CLI
        run: npm i -g vercel@latest

      - name: 🔍 Determine environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "ENV=production" >> $GITHUB_OUTPUT
          else
            echo "ENV=preview" >> $GITHUB_OUTPUT
          fi

      - name: 🚀 Deploy https://manup.dev to Vercel (${{ steps.env.outputs.ENV }})
        run: |
          if [[ "${{ steps.env.outputs.ENV }}" == "production" ]]; then
            vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --target=preview --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: ✉️ Send Message to Slack
        uses: act10ns/slack@v2
        with:
          config: ./slack-config.yml
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ secrets.SLACK_CHANNEL_NAME }}
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
